---
name: Triggered Actions

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types: [created, edited]

jobs:
  task:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run-task' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
