---
name: Triggered Actions

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types: [created, edited]

permissions:
  actions: write
  contents: read
  issues: read
  pull-requests: read

jobs:
  task:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run-task' }}
    runs-on: ubuntu-latest
    steps:

      - name: Get PR details
        uses: actions/github-script@v7
        id: get-pr
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            console.log(`PR ${JSON.stringify(pr)}`);
            return {
              ref: pr.data.head.ref,
              sha: pr.data.head.sha
            }

      - name: Trigger build workflow
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Repo payload:', JSON.stringify(context.repo));
            console.log('Event payload:', JSON.stringify(context.payload, null, 2));
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'task.yml',
              ref: 'main',
              inputs: {
                pr_number: context.issue.number.toString()
              }
            })
