---
name: Triggered Actions

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types: [created, edited]

permissions:
  actions: write
  contents: read
  issues: read
  pull-requests: read

jobs:
  task:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'run-task' }}
    runs-on: ubuntu-latest
    steps:

      - name: Get PR details
        uses: actions/github-script@v7
        id: get-pr
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              ref: pr.data.head.ref,
              sha: pr.data.head.sha
            }

      - name: Trigger build workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'task.yml',
              ref: 'main',
              inputs: {
                pr_number: context.issue.number.toString(),
                branch_ref: pr_data.ref,
                sha: pr_data.sha
              }
            })
